### ISSUE TITLE
Criar Modulo

### ISSUE THREAD

**Issue by lucassoaresouza** [PI2-PLG/PLG-BI#1]
**Descrição**
Construir a classe Modulo e a classe Dados do Modulo:

**Tarefas**

Atributos da classe Modulo:

* nome

Atributos da classe Dados do Modulo:

* data de coleta dos dados
* latitude
* longitude
* temperatura
* umidade
* pressão

Construir views:

* NewModule - permitir a criação de um modulo
* NewModuleData - permitir a criação de um conjunto de dados de um módulo
* GetAllModuleData  - retornar todos os conjuntos de dados de um módulo

**Critérios de Aceitação**

- [x] Classe Modulo
- [x] Classe Dados do Modulo
- [x] View Novo Módulo
- [x] View Novo Dados do Modulo
- [x] View GetAllModuleData

**Comment by mateusroriz** [comment]
Concluído
